# Generated by Django 3.2.10 on 2021-12-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0004_tvshow_thetvdb_id'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.AddField(
            model_name='schedule',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tv_show.tvshow'),
            preserve_default=False,
        ),
    ]
