# Generated by Django 3.2.10 on 2021-12-13 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
        ('schedule', '0002_auto_20211213_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.day'),
        ),
    ]
