# Generated by Django 3.2.10 on 2021-12-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='thread',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
