# Generated by Django 3.2.10 on 2021-12-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subreddit', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='tv_show',
        ),
    ]
