# Generated by Django 3.2.10 on 2021-12-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0002_auto_20211213_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='description',
            new_name='footer',
        ),
    ]
