# Generated by Django 3.2.10 on 2021-12-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0003_rename_description_tvshow_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='thetvdb_id',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
